Feature/#139456269/czar draws card by clicking
andela/izanami-cfh pull request #18
Opened 2017-03-07 22:57 UTC by andela-uibrahim

# What does this PR do?

Add pop up prompting the czar that he is the czar
Add czar draw card functionality
Upload the questions to the DB
Animate the deck of cards

# How should this be manually tested?
by playing the game from the review app and observing this new features

# Any background context you want to provide?
this PR made several file changes and tried to modify most codes in files touched to follow eslint rules

# What are the relevant pivotal tracker stories?
CZARs should be able to draw cards by clicking

# Screenshots (if appropriate)
N/A
# Questions:
N/A

2017-03-08 09:58 UTC, eshaibu submitted a review, later dismissed

2017-03-08 10:39 UTC, eshaibu submitted a review, later dismissed

2017-03-09 13:55 UTC, ooduye requested changes
Review these changes and correct them ASAP

2017-03-09 13:55 UTC, andela-ooduye commented on .gitignore
> -.env
Why did you get rid of the .env from here? The env file is never to be pushed!

2017-03-09 13:55 UTC, andela-ooduye commented on app/views/includes/foot.jade
> +//script(type='text/javascript', src='/lib/jquery/jquery.js')
Why do we have commented out code?

2017-03-09 13:55 UTC, andela-ooduye commented on app/views/includes/foot.jade
> +script(type='text/javascript', src='https://code.jquery.com/jquery-2.2.4.js')
Why are you using a CDN? When the application is created, it already gets the latest version of jquery in the link you commented above

2017-03-09 13:55 UTC, andela-ooduye commented on bower.json
> +    "jquery": "~2.1.4",
Any reason for this change?

2017-03-09 13:55 UTC, andela-ooduye commented on config/socket/game.js
> +//    // console.log(this.gameID,'no cards were picked!');
Remove all commented out code

2017-03-09 13:55 UTC, andela-ooduye commented on config/socket/game.js
> +//    this.stateChoosing(this);
Remove all commented out code

2017-03-09 17:24 UTC, ooduye approved these changes

2017-03-09 17:24 UTC, merged